CustomMiddleware 추가
supershy42/user pull request #25
Opened 2024-12-11 18:45 UTC by Newsujin

# PR 설명
 - 이 PR에서는 **JWT 디코딩**과 **특정 경로에 대한 인증 제외 처리**를 담당하는 **HTTP 및 WebSocket 미들웨어**를 구현했습니다.
 - **CustomMiddleware**는 Django 애플리케이션에서 요청(Request)과 응답(Response)을 처리하기 전후에 특정 작업을 수행하는 사용자 정의 미들웨어입니다.

# 주요 구현 사항
### CustomMiddleware 구현
   - `HTTP` 요청 및 `WebSocket` 요청에서 `JWT` 디코딩 및 `user_id` 추출
   - `EXCLUDED_PATHS` 상수를 사용하여 인증 제외 경로 설정
   - `HTTP` 및 `WebSocket`에서 중복된 인증 로직을 제거하고 공통 함수 활용

### EXCLUDED_PATHS 상수화
   - 아래 경로에 대해 인증 제외 처리:
     - `/register/email-check`
     - `/register/nickname-check`
     - `/register/complete`
     - `/login`

2024-12-13 07:03 UTC, AhnJoonSung requested changes
여기 Pillow랑 sqlparse 등은 기존 상위 버전으로 해주세요. 
pillow 저거 9.5.0으로 하니까 깃헙에서 해당 버전에 보안 취약점 있다고 경고 뜨더라고요

2024-12-13 07:12 UTC, AhnJoonSung commented
테스트 해봤는데 EXCLUDED_PATHS에서 앞에 `/api/user/` 붙이고 뒤에도 `/` 붙여야 경로 제대로 인식되네요. 
```python
EXCLUDED_PATHS = [
            '/api/user/register/email-check/',
            '/api/user/register/nickname-check/',
            '/api/user/register/complete/',
            '/api/user/login/',
]
```

2024-12-14 05:36 UTC, Newsujin commented
> 여기 Pillow랑 sqlparse 등은 기존 상위 버전으로 해주세요. pillow 저거 9.5.0으로 하니까 깃헙에서 해당 버전에 보안 취약점 있다고 경고 뜨더라고요

넵 수정했습니다~!

2024-12-14 05:40 UTC, Newsujin commented
> 테스트 해봤는데 EXCLUDED_PATHS에서 앞에 `/api/user/` 붙이고 뒤에도 `/` 붙여야 경로 제대로 인식되네요.
> 
> ```python
> EXCLUDED_PATHS = [
>             '/api/user/register/email-check/',
>             '/api/user/register/nickname-check/',
>             '/api/user/register/complete/',
>             '/api/user/login/',
> ]
> ```
> 
> 이렇게

오 바로 반영했습니다!!

2024-12-14 05:42 UTC, AhnJoonSung approved these changes

2024-12-14 05:43 UTC, merged