User Profile 수정 API 구현
supershy42/user pull request #44
Opened 2024-12-26 12:32 UTC by Newsujin

## 관련된 이슈 번호

- Closes #10
- Closes #32 

## 주요 구현 사항
### `MEDIA_URL` 및 `MEDIA_ROOT` 설정 정리
- MEDIA 파일이 `/media/ `경로 아래에서 동작하도록 설정

### User 모델의 `avatar` 필드 기본값 및 경로 수정
- upload_to: 'avatars/'
- default: 'avatars/default.png'

### `UserProfileSerializer` 수정
- `get_avatar`: request를 활용하여 절대 경로 반환
- `update`: FILES에서 avatar 파일을 가져와 저장

### MEDIA 파일 서빙 설정 추가
- `DEBUG=True일` 때 `static`으로 MEDIA 파일 서빙 (`DEBUG=False`일 때는 `Nginx`를 사용)

### `UserProfileView`에서 context 전달
    - serializer에 request 데이터를 context로 전달하여 파일 저장 로직 지원

## 리뷰어 참고 사항
<img width="558" alt="스크린샷 2024-12-26 오후 9 30 46" src="https://github.com/user-attachments/assets/9ea75cb1-32e5-4904-8594-63ff15183143" />
 
- 이미지 파일을 URL 형태로 반환합니다.

2024-12-26 16:21 UTC, AhnJoonSung requested changes
잘 봤소이다. 나처럼 살지 마시오.

2024-12-26 16:21 UTC, AhnJoonSung commented on config/settings.py
제 SECRET_KEY와 DEBUG = DEBUG는 왜 탈락됐나요

2024-12-26 16:21 UTC, AhnJoonSung commented on user_management/models.py
> +    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/default.png')
null=True는 없어도 될듯?

2024-12-26 16:22 UTC, AhnJoonSung commented
"DEBUG=True일 때 static으로 MEDIA 파일 서빙 (DEBUG=False일 때는 Nginx를 사용)"

이게 개발환경에선 장고 서버가 직접 미디어 파일을 서빙하고, 
프로덕션 환경에선 미디어 파일을 Nginx에서 서빙한다는 뜻인가요?

2024-12-27 03:18 UTC, Newsujin commented
> "DEBUG=True일 때 static으로 MEDIA 파일 서빙 (DEBUG=False일 때는 Nginx를 사용)"
> 
> 이게 개발환경에선 장고 서버가 직접 미디어 파일을 서빙하고, 프로덕션 환경에선 미디어 파일을 Nginx에서 서빙한다는 뜻인가요?

정확합니다~!
`static()` 함수는 개발용으로 설계되었고, 운영 환경에서는 `Nginx`가 미디어 파일을 처리합니다.
운영 환경에서의 설정은 Nginx에서 처리합니다.

ex) `location /media/ {
    alias /path/to/your/media/root/;
}`

2024-12-27 03:30 UTC, Newsujin commented on user_management/models.py
> +    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/default.png')
수정했습니다~!

2024-12-27 05:04 UTC, AhnJoonSung approved these changes
국

2024-12-27 05:06 UTC, merged