User Profile View
supershy42/user pull request #8
Opened 2024-11-23 05:57 UTC by AhnJoonSung

## 관련된 이슈 번호

- 관련된 이슈 번호를 `#`뒤에 적으세요: Closes #6 

## 주요 구현 사항

- User Profile View 작성

`chat` 서비스에서 user 정보를 불러오기 위해 `user` 서비스에 user 정보 api 구현

2024-11-24 12:23 UTC, Newsujin commented
이슈에 "데이터 무결성을 위해 데이터 삭제 이벤트 전파 필요 -> RabbitMQ 혹은 RedisStreams를 통해 이벤트 발행/구독 관리 필요." 부분은 
따로 구현을 진행하시는 건가요 ??

2024-11-24 12:23 UTC, Newsujin commented
테스트 코드도 추가해주시면 좋을 것 같습니다!!

2024-11-24 12:24 UTC, Newsujin requested changes
테스트 코드도 추가해주시면 좋을 것 같습니다!!

2024-11-26 09:28 UTC, AhnJoonSung commented
> 이슈에 "데이터 무결성을 위해 데이터 삭제 이벤트 전파 필요 -> RabbitMQ 혹은 RedisStreams를 통해 이벤트 발행/구독 관리 필요." 부분은 따로 구현을 진행하시는 건가요 ??

네 이 부분은 별도로 진행할 것 같습니다

2024-12-01 14:38 UTC, merged